#!/usr/bin/env node
import { confirm, select } from "@inquirer/prompts";
import { access, readdir, stat, rm, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const PACKAGE_NAME = "shane-new-post";

// --lang=en / --lang=zh-cn picks the language up front (shorthands --en /
// --zh-cn / --zh / --chinese / --english also work). If none is given and
// this is an interactive terminal, we ask once here and forward the answer
// to the installed package via SHANE_CLI_LANG so its own postinstall prompt
// doesn't have to ask again.
const rawArgs = process.argv.slice(2);

function normalizeLangFlag(argv) {
  for (const arg of argv) {
    if (arg === "--zh-cn" || arg === "--zh" || arg === "--chinese") return "zh-cn";
    if (arg === "--en" || arg === "--english") return "en";
    const match = arg.match(/^--lang=(.+)$/i);
    if (match) {
      const value = match[1].toLowerCase();
      if (value.startsWith("zh")) return "zh-cn";
      if (value.startsWith("en")) return "en";
    }
  }
  return null;
}

async function resolveLang() {
  const fromFlag = normalizeLangFlag(rawArgs);
  if (fromFlag) return fromFlag;

  if (process.env.SHANE_CLI_LANG) {
    const value = process.env.SHANE_CLI_LANG.toLowerCase();
    if (value.startsWith("zh")) return "zh-cn";
    if (value.startsWith("en")) return "en";
  }

  if (!process.stdin.isTTY) return null; // let the package's own postinstall guess from locale

  let guess = "en";
  try {
    const locale = Intl.DateTimeFormat().resolvedOptions().locale || "";
    if (locale.toLowerCase().startsWith("zh")) guess = "zh-cn";
  } catch {
    // ignore, keep default guess
  }

  try {
    return await select({
      message: "Select CLI language / 选择界面语言:",
      choices: [
        { name: "English", value: "en" },
        { name: "简体中文", value: "zh-cn" },
      ],
      default: guess,
    });
  } catch {
    return null;
  }
}

// Marker written at the top of generated files -- a file carrying this
// marker means it's already been taken over by this package. Used to detect
// whether postinstall has actually run yet, to avoid asking again.
const MANAGED_MARKER = `// @generated by ${PACKAGE_NAME}`;

const CANDIDATE_NAMES = [
  "new-post.js",
  "new post.js",
  "new-blog.js",
  "new blog.js",
  "newpost.js",
  "newblog.js",
  "new posts.js",
  "new-posts.js",
  "newposts.js",
  "new blogs.js",
  "new-blogs.js",
  "newblogs.js",
];

async function exists(path) {
  try { await access(path); return true; }
  catch { return false; }
}

async function isAlreadyManaged(filePath) {
  if (!(await exists(filePath))) return false;
  try {
    const content = await readFile(filePath, "utf8");
    return content.slice(0, 200).includes(MANAGED_MARKER);
  } catch {
    return false;
  }
}

async function findScriptConflicts(names) {
  const ignore = new Set(["node_modules", ".git"]);
  const folders = ["script", "scripts"];
  const lowerNames = names.map((x) => x.toLowerCase());
  const results = [];

  async function scan(dir) {
    for (const item of await readdir(dir)) {
      if (ignore.has(item)) continue;
      const full = join(dir, item);
      const info = await stat(full);

      if (info.isDirectory()) {
        if (folders.some((f) => f.toLowerCase() === item.toLowerCase())) {
          for (const file of await readdir(full)) {
            const candidate = join(full, file);
            // Files already generated by this package aren't conflicts, skip
            // them so a rerun doesn't mistakenly flag them for deletion
            if (lowerNames.includes(file.toLowerCase()) && !(await isAlreadyManaged(candidate))) {
              results.push({ path: candidate, inScriptFolder: true });
            }
          }
        }
        await scan(full);
      } else if (lowerNames.includes(item.toLowerCase()) && !(await isAlreadyManaged(full))) {
        results.push({ path: full, inScriptFolder: false });
      }
    }
  }

  await scan(".");
  return results;
}

// Checks the scripts/script directory for a script already managed by this
// package
async function findManagedScript() {
  for (const dirName of ["scripts", "script"]) {
    if (!(await exists(dirName))) continue;
    for (const name of CANDIDATE_NAMES) {
      const candidate = join(dirName, name);
      if (await isAlreadyManaged(candidate)) return candidate;
    }
  }
  return null;
}

// Detects which package manager was used to invoke the create command via
// the npm_config_user_agent env var (same one npm/pnpm/yarn set), so the
// dependency gets installed with the same tool
function detectPackageManager() {
  const ua = process.env.npm_config_user_agent || "";
  if (ua.startsWith("pnpm")) return "pnpm";
  if (ua.startsWith("yarn")) return "yarn";
  if (ua.startsWith("npm")) return "npm";

  if (existsSync("pnpm-lock.yaml")) return "pnpm";
  if (existsSync("yarn.lock")) return "yarn";
  if (existsSync("package-lock.json")) return "npm";

  return "pnpm";
}

function installCommand(pm, pkgName) {
  switch (pm) {
    case "pnpm": return { cmd: "pnpm", args: ["add", pkgName] };
    case "yarn": return { cmd: "yarn", args: ["add", pkgName] };
    default: return { cmd: "npm", args: ["install", pkgName, "--save"] };
  }
}

try {
  const lang = await resolveLang();
  // Forwarded to the installed package's own postinstall (and to a manual
  // postinstall.js run below) via the environment, since a package manager's
  // own lifecycle-script invocation doesn't let us pass extra argv.
  const spawnEnv = lang ? { ...process.env, SHANE_CLI_LANG: lang } : process.env;

  const conflicts = await findScriptConflicts(CANDIDATE_NAMES);

  for (const item of conflicts) {
    const remove = await confirm({
      message: `Found ${item.path}, which matches this package's script naming convention and may conflict. Delete it?`,
      initial: true,
    });

    if (remove) {
      await rm(item.path);
      console.log(`Deleted conflicting script: ${item.path}`);
    }
  }

  if (!existsSync("package.json")) {
    console.error("❌ No package.json found in the current directory. Run this in the root of your Astro blog project.");
    process.exit(1);
  }

  const pm = detectPackageManager();
  const { cmd, args } = installCommand(pm, PACKAGE_NAME);

  console.log(`\n📦 Installing ${PACKAGE_NAME} with ${pm}...\n`);

  const installResult = spawnSync(cmd, args, {
    stdio: "inherit",
    shell: process.platform === "win32",
    env: spawnEnv,
  });

  if (installResult.error || installResult.status !== 0) {
    console.error(`\n❌ "${cmd} ${args.join(" ")}" failed. Check your network/package manager setup and try again.`);
    process.exit(installResult.status || 1);
  }

  // Some package managers (e.g. newer pnpm) skip lifecycle scripts for new
  // dependencies by default, so double-check here: if the script still
  // hasn't been generated after install, run the package's own
  // postinstall.js manually to guarantee this command finishes "installed".
  const alreadyManaged = await findManagedScript();

  if (!alreadyManaged) {
    const postinstallPath = join("node_modules", PACKAGE_NAME, "bin", "postinstall.js");

    if (existsSync(postinstallPath)) {
      console.log("\nℹ️ Your package manager didn't run the install script automatically, running it manually...\n");
      const runResult = spawnSync("node", [postinstallPath], { stdio: "inherit", env: spawnEnv });

      if (runResult.error || runResult.status !== 0) {
        console.error("\n❌ postinstall script failed");
        process.exit(runResult.status || 1);
      }
    } else {
      console.error(`\n⚠️ ${postinstallPath} not found. The install may be incomplete, try running "${pm} install" manually.`);
      process.exit(1);
    }
  }

  console.log("\nInitialization complete. Run: pnpm new-post");
} catch (error) {
  if (error.name === "ExitPromptError") process.exit(0);
  console.error(error);
  process.exit(1);
}
